version: "1.0"

services:
  php-fpm:
    container_name: docker_for_slim_fpm
    build:
      context: ./docker/php-fpm
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/project

  nginx:
    container_name: docker_for_slim_nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - .:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-fpm